theme: 
  - osuny
  - osuny-plugin-centered-footer
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: ''
    footer: ''
  home:
    head:
      title: site