[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/equipe/"
to = "/fr/personnes/"

[[redirects]]
from = "/agenda/2025/"
to = "/fr/agenda/2025/"

[[redirects]]
from = "/accessibilite/"
to = "/fr/accessibilite/"

[[redirects]]
from = "/organisations/"
to = "/fr/organisations/"

[[redirects]]
from = "/agenda/2026/05/"
to = "/fr/agenda/2026/05/"

[[redirects]]
from = "/actualites/"
to = "/fr/actualites/"

[[redirects]]
from = "/agenda/"
to = "/fr/agenda/"

[[redirects]]
from = "/agenda/2025/seance-1-seminaire-ia-et-democratie-2025-2026/"
to = "/fr/agenda/2025/seance-1-seminaire-ia-et-democratie-2025-2026/"

[[redirects]]
from = "/projets/2025-avec-jacques-ellul/"
to = "/fr/projets/2025-avec-jacques-ellul/"

[[redirects]]
from = "/equipe/equipe-editoriale/"
to = "/fr/personnes/equipe-editoriale/"

[[redirects]]
from = "/cv/"
to = "/fr/cv/"

[[redirects]]
from = "/recherche/"
to = "/fr/recherche/"

[[redirects]]
from = "/agenda/2025/seance-2-seminaire-ia-et-democratie-2025-2026-avec-jean-cattan-conseil-de-lia-et-du-numerique/"
to = "/fr/agenda/2025/seance-2-seminaire-ia-et-democratie-2025-2026-avec-jean-cattan-conseil-de-lia-et-du-numerique/"

[[redirects]]
from = "/personnes/"
to = "/fr/personnes/"

[[redirects]]
from = "/publications/"
to = "/fr/publications/"

[[redirects]]
from = "/expositions/"
to = "/fr/expositions/"

[[redirects]]
from = "/agenda/2026/06/"
to = "/fr/agenda/2026/06/"

[[redirects]]
from = "/mentions-legales/"
to = "/fr/mentions-legales/"

[[redirects]]
from = "/plan-du-site/"
to = "/fr/plan-du-site/"

[[redirects]]
from = "/politique-de-confidentialite/"
to = "/fr/politique-de-confidentialite/"

[[redirects]]
from = "/personnes/equipe-editoriale/"
to = "/fr/personnes/equipe-editoriale/"

[[redirects]]
from = "/agenda/2026/02/"
to = "/fr/agenda/2026/02/"

[[redirects]]
from = "/projets/"
to = "/fr/projets/"

[[redirects]]
from = "/expositions/archives-expositions/"
to = "/fr/expositions/archives-expositions/"

[[redirects]]
from = "/agenda/2026/04/"
to = "/fr/agenda/2026/04/"

[[redirects]]
from = "/projets/2025-lia-aux-frontieres-de-lesprit/"
to = "/fr/projets/2025-lia-aux-frontieres-de-lesprit/"

[[redirects]]
from = "/enseignements/"
to = "/fr/enseignements/"

[[redirects]]
from = "/agenda/2026/"
to = "/fr/agenda/2026/"

[[redirects]]
from = "/agenda/2025/11/"
to = "/fr/agenda/2025/11/"

