[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/equipe/index.html"
to = "/fr/personnes/"

[[redirects]]
from = "/agenda/2025/index.html"
to = "/fr/agenda/2025/"

[[redirects]]
from = "/accessibilite/index.html"
to = "/fr/accessibilite/"

[[redirects]]
from = "/organisations/index.html"
to = "/fr/organisations/"

[[redirects]]
from = "/agenda/2026/05/index.html"
to = "/fr/agenda/2026/05/"

[[redirects]]
from = "/actualites/index.html"
to = "/fr/actualites/"

[[redirects]]
from = "/agenda/index.html"
to = "/fr/agenda/"

[[redirects]]
from = "/agenda/2025/seance-1-seminaire-ia-et-democratie-2025-2026/index.html"
to = "/fr/agenda/2025/seance-1-seminaire-ia-et-democratie-2025-2026/"

[[redirects]]
from = "/projets/2025-avec-jacques-ellul/index.html"
to = "/fr/projets/2025-avec-jacques-ellul/"

[[redirects]]
from = "/equipe/equipe-editoriale/index.html"
to = "/fr/personnes/equipe-editoriale/"

[[redirects]]
from = "/cv/index.html"
to = "/fr/cv/"

[[redirects]]
from = "/recherche/index.html"
to = "/fr/recherche/"

[[redirects]]
from = "/agenda/2025/seance-2-seminaire-ia-et-democratie-2025-2026-avec-jean-cattan-conseil-de-lia-et-du-numerique/index.html"
to = "/fr/agenda/2025/seance-2-seminaire-ia-et-democratie-2025-2026-avec-jean-cattan-conseil-de-lia-et-du-numerique/"

[[redirects]]
from = "/personnes/index.html"
to = "/fr/personnes/"

[[redirects]]
from = "/publications/index.html"
to = "/fr/publications/"

[[redirects]]
from = "/expositions/index.html"
to = "/fr/expositions/"

[[redirects]]
from = "/agenda/2026/06/index.html"
to = "/fr/agenda/2026/06/"

[[redirects]]
from = "/mentions-legales/index.html"
to = "/fr/mentions-legales/"

[[redirects]]
from = "/plan-du-site/index.html"
to = "/fr/plan-du-site/"

[[redirects]]
from = "/politique-de-confidentialite/index.html"
to = "/fr/politique-de-confidentialite/"

[[redirects]]
from = "/personnes/equipe-editoriale/index.html"
to = "/fr/personnes/equipe-editoriale/"

[[redirects]]
from = "/agenda/2026/02/index.html"
to = "/fr/agenda/2026/02/"

[[redirects]]
from = "/projets/index.html"
to = "/fr/projets/"

[[redirects]]
from = "/expositions/archives-expositions/index.html"
to = "/fr/expositions/archives-expositions/"

[[redirects]]
from = "/agenda/2026/04/index.html"
to = "/fr/agenda/2026/04/"

[[redirects]]
from = "/projets/2025-lia-aux-frontieres-de-lesprit/index.html"
to = "/fr/projets/2025-lia-aux-frontieres-de-lesprit/"

[[redirects]]
from = "/enseignements/index.html"
to = "/fr/enseignements/"

[[redirects]]
from = "/agenda/2026/index.html"
to = "/fr/agenda/2026/"

[[redirects]]
from = "/agenda/2025/11/index.html"
to = "/fr/agenda/2025/11/"

